version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo

jobs:
  test:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run database migrations
          command: |
            python manage.py migrate
      - run:
          name: Run tests
          command: |
            python manage.py test
    environment:
      DJANGO_SETTINGS_MODULE: student_management.settings
      DATABASE_URL: postgres://student_management:student_management@localhost:5432/student_management

workflows:
  version: 2
  test:
    jobs:
      - test
