version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run database migrations
          command: |
            python manage.py migrate
      - run:
          name: Run tests
          command: |
            coverage run --source='.' manage.py test
      - run:
          name: Generate coverage report
          command: |
            coverage xml
      - codecov/upload:
          file: ./coverage.xml

workflows:
  version: 2
  test:
    jobs:
      - test
